# Generated by Django 5.1.6 on 2025-03-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
